---
name: MineParty
version: 2.2.0
main: MCA7\MineParty\Main
api: [ 4.0.0, 5.0.0 ] 
depend: BedrockEconomy

commands:
  mineparty:
    usage: "/mineparty <join/quit>"
    permission: mineparty.command
    aliases: [mp]

permissions:
  mineparty.command:
    default: true
  mineparty.admin:
    description: "/mineparty start"
    default: op
...
