---
name: MineParty
version: 1.0.0
main: MCA7\MineParty\Main
api: 3.20.0
depend: EconomyAPI

commands:
  mineparty:
    usage: "/mineparty <join/quit>"
    aliases: [mp]

permissions:
  mineparty.admin:
    description: "/mineparty start"
    default: op
...
