---
name: MineParty
version: 2.0.0
main: MCA7\MineParty\Main
api: 4.0.0
depend: EconomyAPI

commands:
  mineparty:
    usage: "/mineparty <join/quit>"
    permission: mineparty.command
    aliases: [mp]

permissions:
  mineparty.command:
    default: true
  mineparty.admin:
    description: "/mineparty start"
    default: op
...
