#   __  __   _                  ____                   _
#  |  \/  | (_)  _ __     ___  |  _ \    __ _   _ __  | |_   _   _
#  | |\/| | | | | '_ \   / _ \ | |_) |  / _` | | '__| | __| | | | |
#  | |  | | | | | | | | |  __/ |  __/  | (_| | | |    | |_  | |_| |
#  |_|  |_| |_| |_| |_|  \___| |_|      \__,_| |_|     \__|  \__, |
#                                                            |___/
# Copyright (C) 2021 MCA7#1245

# How long will the MineParty last?
minutes: 1

# How much $$ will the winner receive per block mined? (Integer)
price-money: 1000

# TODO => Messages
