# ========================
# MineParty by MCA7#1245
# ========================
# Copyright(C) 2021

# How long will the MineParty last? (Longer time = more stress on the server)
minutes: 1
# Rewards
money-per-block-mined: 1000
